targets:
  $default:
    builders:
      builder_static_text|static_text:
        generate_for:
          - lib/**/*.dart
        options:
          content: '// ignore_for_file: strong_mode_implicit_dynamic_parameter, implicit_dynamic_parameter, implicit_dynamic_variable'
