name: dc2f_edit_client_desktop
description: An example project for flutter-desktop-embedding.

environment:
  sdk: '>=2.2.2 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.5.8'

dependencies:
  pedantic: '1.7.0'
  provider: ^2.0.1
  dio: ^2.1.3
  logging: ^0.11.3+2
  json_annotation: ^2.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  json_serializable: ^2.3.0
  builder_static_text: ^0.0.1
  build_runner: ^1.4.0
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
